import { Inter } from "next/font/google";
import "./globals.css";
// import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Medinsync",
	description: "Generated by SKill-Issue",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
